### ISSUE TITLE
Logger not bound to the right context

### ISSUE THREAD

**Issue by vhf** [zazuko/barnard59#112]
I had issues with the logger in barnard59-kafka, where the logger wasn't bound to its correct context. This PR solves issues such as:

```
this.consumer.on('data', logger.info)
```

which gave:

```
/myproject/node_modules/barnard59-core/lib/logger.js:42
    this.writeLog(lvl, message, details)
         ^

TypeError: this.writeLog is not a function
    at KafkaConsumerStream.Logger.(anonymous function) (/myproject/node_modules/barnard59-core/lib/logger.js:42:10)
    at KafkaConsumerStream.emit (events.js:194:15)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at KafkaConsumerStream.Readable.push (_stream_readable.js:220:10)
    at onread (/mylibs/zazuko/barnard59-kafka/node_modules/node-rdkafka/lib/kafka-consumer-stream.js:207:14)
    at /mylibs/zazuko/barnard59-kafka/node_modules/node-rdkafka/lib/kafka-consumer.js:460:7
```

I could probably create a repro for this bug if you show me a repo with a minimal pipeline that has a single JS operation and enters it only once.

Fixed in zazuko/barnard59-core#40

**Comment by bergos** [comment]
@vhf can we close this issue?

**Comment by vhf** [comment]
Thanks!

**Comment by vhf** [comment]
@bergos I remember why we didn't close this earlier: we wanted to add a test for this but I needed a very basic pipeline example to be able to reproduce, something that only has one operation implemented in a file alongside the test pipeline.
