### ISSUE TITLE
Improve error output when multiple pipelines are found

### ISSUE THREAD

**Issue by tpluscode** [zazuko/barnard59#160]
When running the CLI and multiple pipeline are found an error is displayed similar to

```
node bin/barnard59.js run examples/fetch-json-to-ntriples.ttl
Error: Multiple root pipelines found.
    at findPipeline (file:///Volumes/Home/projects/zazuko/barnard59/packages/cli/findPipeline.js:22:11)
    at file:///Volumes/Home/projects/zazuko/barnard59/packages/cli/lib/cli/runAction.js:44:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Command.default (file:///Volumes/Home/projects/zazuko/barnard59/packages/cli/lib/cli/runAction.js:39:3)
    at async Promise.all (index 0)
    at async default (file:///Volumes/Home/projects/zazuko/barnard59/packages/cli/lib/cli.js:28:3)
    at async file:///Volumes/Home/projects/zazuko/barnard59/packages/cli/bin/barnard59.js:94:3
```

We should improve that output:

1. Remove the stack trace
2. List the possible options, ideally as copy/paste, ready-to-use command with actual URIs found in the definition

```
node bin/barnard59.js run examples/fetch-json-to-ntriples.ttl
Error: Multiple root pipelines found. 
  Try one of these:
     `--pipeline http://example.com/root`
     `--pipeline http://example.com/second`
```

**Comment by tpluscode** [comment]
To check whether the CLI really finds only root pipeline or also considers subpipelines when this error is shown. In that case we may have a bug

**Comment by giacomociti** [comment]
before throwing, non-root pipelines are discarded, so the behavior is correct, we just need to improve the error message
